[theme]
name = "garden"
desc = "A relaxing nature rice inspired by the movie Garden of Words"
version = "1.0"
author = "BeardWarrior"
git = "https://github.com/taylor85345/garden-hyprland-theme"
config = "theme.conf"

[kill]
exclude_bar = ["eww"]
exclude_wallpaper = ["swaybg,mpvpaper"]
